feat(api-gateway): support non api gateway
AccelByte/wordpress-react-plugin pull request #2
Opened 2021-09-14 01:48 UTC by argadityars

Closes CLD-973

2021-09-14 06:22 UTC, klepon requested changes
got error

**Unhandled Rejection (TypeError): Cannot read property 'avatarUrl' of undefined**

UserProfileButton.render
src/components/Auth/UserProfileButton.tsx:83
```
  80 | >
  81 |   <Avatar
  82 |     isLoading={isFetchingProfile}
> 83 |     imageUrl={profile!.avatarUrl}
  84 | ^   className={classNames(
  85 |       "ab-wpr-avatar",
  86 |       {"large": screenWidth >= breakPoint.medium.max},
```

2021-09-14 06:22 UTC, klepon commented on widget/src/utils/env.ts
> +export const redirectURI = process.env.CLIENT_REDIRECT_URI || (isDevMode && "https://versusevil.com") || "";
can we revert this into demo.accelbyte.io instead?
also for other changes below

2021-09-14 07:37 UTC, argadityars commented on widget/src/utils/env.ts
> +export const redirectURI = process.env.CLIENT_REDIRECT_URI || (isDevMode && "https://versusevil.com") || "";
ah my bad, will update it to demo

2021-09-14 07:39 UTC, THZs commented on README.md
> +- `JUSTICE_BASE_URL` - URL of your AccelByte APIGateway
We don't use API Gateway anymore, how if we change the description to "Base URL of Accelbyte services"?

2021-09-14 09:15 UTC, argadityars commented
> got error
> 
> **Unhandled Rejection (TypeError): Cannot read property 'avatarUrl' of undefined**
> 
> UserProfileButton.render
> src/components/Auth/UserProfileButton.tsx:83
> 
> ```
>   80 | >
>   81 |   <Avatar
>   82 |     isLoading={isFetchingProfile}
> > 83 |     imageUrl={profile!.avatarUrl}
>   84 | ^   className={classNames(
>   85 |       "ab-wpr-avatar",
>   86 |       {"large": screenWidth >= breakPoint.medium.max},
> ```

I didn't make any changes into this file, and actually I can build the project without getting this error. can you tell me how to reproduce this?

2021-09-15 08:06 UTC, klepon commented
> > got error
> > **Unhandled Rejection (TypeError): Cannot read property 'avatarUrl' of undefined**
> > UserProfileButton.render
> > src/components/Auth/UserProfileButton.tsx:83
> > ```
> >   80 | >
> >   81 |   <Avatar
> >   82 |     isLoading={isFetchingProfile}
> > > 83 |     imageUrl={profile!.avatarUrl}
> >   84 | ^   className={classNames(
> >   85 |       "ab-wpr-avatar",
> >   86 |       {"large": screenWidth >= breakPoint.medium.max},
> > ```
> 
> I didn't make any changes into this file, and actually I can build the project without getting this error. can you tell me how to reproduce this?

i see this from current master branch, is nice if this can be fixed as well, it fixed using `imageUrl={profile ? profile!.avatarUrl : ""}`
the error occur on browser when run `yarn start` or after build when it use on WP the js script error causing it not working

2021-09-16 01:57 UTC, argadityars commented
> > > got error
> > > **Unhandled Rejection (TypeError): Cannot read property 'avatarUrl' of undefined**
> > > UserProfileButton.render
> > > src/components/Auth/UserProfileButton.tsx:83
> > > ```
> > >   80 | >
> > >   81 |   <Avatar
> > >   82 |     isLoading={isFetchingProfile}
> > > > 83 |     imageUrl={profile!.avatarUrl}
> > >   84 | ^   className={classNames(
> > >   85 |       "ab-wpr-avatar",
> > >   86 |       {"large": screenWidth >= breakPoint.medium.max},
> > > ```
> > 
> > 
> > I didn't make any changes into this file, and actually I can build the project without getting this error. can you tell me how to reproduce this?
> 
> i see this from current master branch, is nice if this can be fixed as well, it fixed using `imageUrl={profile ? profile!.avatarUrl : ""}`
> the error occur on browser when run `yarn start` or after build when it use on WP the js script error causing it not working
> 
> btw it happen on SBZ project

okay, it's updated now

2021-09-16 02:01 UTC, klepon approved these changes

2021-09-16 02:47 UTC, THZs commented
> got error
> 
> **Unhandled Rejection (TypeError): Cannot read property 'avatarUrl' of undefined**
> 
> UserProfileButton.render
> src/components/Auth/UserProfileButton.tsx:83
> 
> ```
>   80 | >
>   81 |   <Avatar
>   82 |     isLoading={isFetchingProfile}
> > 83 |     imageUrl={profile!.avatarUrl}
>   84 | ^   className={classNames(
>   85 |       "ab-wpr-avatar",
>   86 |       {"large": screenWidth >= breakPoint.medium.max},
> ```

What @klepon mentioned here is correct. I think I missed this one during writing this.
It should be using [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) instead of [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator). Can you please help to update it also @argaditya-ab ?
I think by changing the `!` mark to `?` would be enough.

2021-09-16 02:50 UTC, THZs approved these changes

2021-09-16 03:10 UTC, merged