docs: add feature flow documentation
AccelByte/wordpress-react-plugin pull request #4
Opened 2021-12-06 07:50 UTC by ab-sandy

2021-12-07 02:02 UTC, argaditya-ab approved these changes

2021-12-07 02:02 UTC, argaditya-ab commented on features-doc/HEADLESS_ACCOUNT.md
> +    - **POST /iam/v3/public/namespaces/{namespace}/users/me/code/request** to get verification code. The context should be upgradeHeadlessAccount.
please wrap `upgradeHeadlessAccount` with code tag

2021-12-07 02:02 UTC, argaditya-ab commented on features-doc/LOGIN.md
> +    - Redirection URL format: {clientRedirectUri}/?code={code}&state={state}
please wrap `{clientRedirectUri}/?code={code}&state={state}` with code tag

2021-12-08 02:18 UTC, THZs requested changes

2021-12-08 02:18 UTC, THZs commented on widget/src/index.tsx
> +if (document.getElementById(ElementSelector.AppRootId)) {
This element is mandatory to be exist, please also print an error message to the console if this element doesn't exist.

2021-12-08 02:18 UTC, THZs commented on widget/src/index.tsx
> +if (document.getElementById(ElementSelector.AuthButtonRootId)) {
How if we make it like this?
```
export const ElementSelector = {
  AppRootId: document.getElementById("ab-wpr-root"),
  AuthButtonRootId: document.getElementById("ab-wpr-login-button-root"),
  AuthButtonRootMobileId: document.getElementById("ab-wpr-login-button-root-mobile"),
  FooterPrivacyLinkId: document.getElementById("ab-wpr-footer-privacy-link"),
  PurchaseButtonClassName: document.getElementById("ab-wpr-purchase-btn")
};

if (ElementSelector.AuthButtonRootId) {
  ReactDOM.render(
    <Provider inject={[appState, appState.state.userSession]}>
      <LoginButton/>
    </Provider>
    , ElementSelector.AuthButtonRootId);
}
```

2021-12-08 02:43 UTC, THZs approved these changes

2021-12-08 08:45 UTC, merged